---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04
  - name: ubuntu-7.7

suites:
  - name: default
    run_list:
      - recipe[mozilla-firefox-sync::default]
    attributes:
